### PR TITLE
Fixes #106

### LINKED ISSUE #106: Duplicate student table header
screen shot 2016-03-21 at 14 49 14

### PR DESCRIPTION
**Pull request by simoneduca**

### CODE REVIEW

**Comment by shaunanoordin** [comment]
I've noted some wonkiness here:

screen shot 2016-03-21 at 17 36 05

Issue: When a classroom displays the "No students in here yet" message, the message appears outside of the the table and doesn't properly go away.
Replication:
- Select a classroom with no students.
- Now open the "Students" tab of that Classroom
- The message "No students in here yet" will appear outside of the <table>
- Now select a classroom with at least one student. The "Student" tab should have still been selected.
- Note that the "No students in here yet" message still appears, above the <table> listing the students.

Analysis:
- The "No students in here yet" appears as a string within `<tbody>` element, which causes the element to act wonky.
- React refuses to render a string as a child of a `<tbody>`, so it renders the string outside of the `tbody`.
- As a result, when new (student) data appears in `<tbody>`, the previous "No students in here yet" string isn't erased by the update to `tbody`.

Recommendations:
- Either add <tr><td colspan="3">...</td></tr>...

```
        <tbody>
          { (filteredList.length > 0) ? filteredList.map((attributes, i) =>
          <tr key={i}>
            <td>{attributes.zooniverse_display_name}</td>
            <td>{attributes.classifications_count}</td>
            <td><button className="btn btn-warning" role="button">Remove</button></td>
          </tr>
          ) : <tr><td colspan="3">No students in here yet</td></tr> }
        </tbody>
```
- ...or wrap the `<table>` in an if operator

```
    <div>
      {(filteredList.length > 0) ?
        <table className="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Classifications</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {filteredList.map((attributes, i) =>
            <tr key={i}>
              <td>{attributes.zooniverse_display_name}</td>
              <td>{attributes.classifications_count}</td>
              <td><button className="btn btn-warning" role="button">Remove</button></td>
            </tr>
            )}
          </tbody>
        </table>
      : 'No students here yet' }
    </div>
```

Tested on Chrome49+MacbookPro+OSX

**Comment by simoneduca** [comment]
Sorry @shaunanoordin I can't reproduce. This is what I get 
screen shot 2016-03-21 at 22 08 22

**Comment by simoneduca** [comment]
However I liked your latter suggestion, so I went with that. Should be good to go now @shaunanoordin, thanks.

**Comment by shaunanoordin** [comment]
Status: **Looks good to me!**
Actions: **Merging**

**Pull request merged**
