### PR TITLE
New classroom form

### PR DESCRIPTION
**Pull request by simoneduca**

### CODE REVIEW

**Comment by simoneduca** [comment]
@shaunanoordin ready to review.

**Comment by shaunanoordin** [comment]
Code looks legit and the functionality of the Add New Classroom form works! I only have a few queries before I merge:

Q1: Just to confirm, `react-router` was upgraded to v2.0.0 for the `browserHistory` functionality, right?
Q2: The (optional) 'Subject' field of a class, after being set during the Add New Classroom process, isn't displayed anywhere. I assume this is a minor functionality that's coming in a later feature branch?

Notes:
- Unintended behaviour can be created by logging in & going to the Classrooms page, then clicking the Logout... because the page still LOOKS like you're logged in, allowing you to access Classroom and Add New Classroom features. (Although any attempt to actually add a new classroom while not logged in will fail silently)
- However, this is NOT a blocking factor for this branch - this is more related to Issue #26: Authentication priorities.

**Comment by simoneduca** [comment]
@shaunanoordin 1) `react-router` has been upgraded because some feats of the older API will stop being supported/are already deprecated, e.g. mixins, history.transitionTo, etc.
2) correct
Notes should be taken care of when routes are properly authenticated.

**Comment by shaunanoordin** [comment]
- Code sanity check passed
- Add New Classroom functionality verified.

PR Status: **Validated**
Action: **Merging**

**Pull request merged**
